# Generated by Django 5.2.5 on 2026-09-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_add_is_hidden_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('complete', 'Complete'), ('cancel', 'Cancel')], default='pending', max_length=20),
        ),
    ]
